version: '3.8'
services:
  bike-backend:
    build: .
    container_name: bike_rental_api
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PORT=5000
      - DB_URL=your_database_url
